export const defaultUsers = [
  {
    username: 'operator01',
    password: 'RedTeam@123',
    role: 'operator',
    email: 'operator01@incognitrix.local',
    registrationNumber: 'INC-OP-0001',
  },
  {
    username: 'admin01',
    password: 'AdminControl@123',
    role: 'admin',
    email: 'admin01@incognitrix.local',
    registrationNumber: 'INC-ADM-0001',
  },
]

export const defaultPlatformConfig = {
  routes: {
    dashboard: true,
    learningPaths: true,
    practiceLabs: true,
    profile: true,
  },
  features: {
    labRooms: true,
    featuredPath: true,
    newMissionButton: true,
    navbarSearch: true,
    navbarNotifications: true,
    navbarSettings: true,
    publicRegistration: true,
    registrationDynamicMin: 23,
    registrationDynamicMax: 30,
  },
  ai: {
    model: 'openai/gpt-oss-120b',
  },
  api: {
    ai: {
      baseUrl: '',
      apiKeyConfigured: false,
      temperature: '',
      topP: '',
      maxTokens: '',
    },
    ctftime: {
      enabled: true,
      baseUrl: 'https://ctftime.org/api/v1',
      userAgent: 'Minerva-Academy/1.0 upcoming event sync',
      limit: 100,
      horizonDays: 365,
    },
    publicApi: {
      keysConfigured: false,
      keyCount: 0,
    },
  },
}

export const defaultRooms = [
  {
    id: 'sql-injection-the-basement',
    slug: 'sql-injection-the-basement',
    category: 'Web Exploitation',
    level: 'Easy',
    levelTone: 'text-emerald-600',
    dotTone: 'bg-emerald-500',
    title: 'SQL Injection: The Basement',
    description: 'Analyze a legacy employee portal and extract encrypted credentials from the underlying database using union-based injection.',
    xp: '500 XP',
    difficulty: 'Easy',
    estimateTime: '45 minutes',
    environment: 'Web Browser + SQL Sandbox',
    categoryTag: 'Web Exploitation',
    tags: ['Database', 'SQL'],
    requiredKeywords: ['UNION', 'WHERE', 'SELECT'],
    content: {
      markdown: '# SQL Injection: The Basement - Intel',
      html: '<section><h2>MISSION_OVERVIEW</h2></section>',
      missionOverview: 'Infiltrate the deprecated Basement authentication portal and identify exploitable SQL input handling flaws.',
      remediationProtocols: 'Apply parameterized queries, enforce strict input validation, and implement least-privilege database access.',
      vulnerabilityBriefing: {
        definition: 'SQL Injection is a vulnerability where untrusted input alters backend SQL query logic.',
        impact: 'Can lead to data theft, authentication bypass, and in severe cases full database compromise.',
      },
      technicalDeepDive: 'The query builder concatenates user input directly into SQL statements without sanitization or prepared statements.',
    },
  },
  {
    id: 'broken-keypad-rsa-101',
    slug: 'broken-keypad-rsa-101',
    category: 'Cryptography',
    level: 'Medium',
    levelTone: 'text-amber-600',
    dotTone: 'bg-amber-500',
    title: 'Broken Keypad: RSA 101',
    description: 'A faulty encryption protocol is leaking prime factors. Intercept the handshake and decrypt the mission-critical command.',
    xp: '1,250 XP',
    difficulty: 'Medium',
    estimateTime: '60 minutes',
    environment: 'Crypto VM',
    categoryTag: 'Cryptography',
    tags: ['Cryptography', 'RSA'],
    requiredKeywords: ['RSA', 'prime factors'],
    content: {
      markdown: '# Broken Keypad: RSA 101',
      html: '<section><h2>RSA Cryptography Challenge</h2></section>',
      missionOverview: '',
      remediationProtocols: '',
      vulnerabilityBriefing: { definition: '', impact: '' },
      technicalDeepDive: '',
    },
  },
  {
    id: 'kernel-panic-buffer-overflow',
    slug: 'kernel-panic-buffer-overflow',
    category: 'Binary Exploitation',
    level: 'Hard',
    levelTone: 'text-primary',
    dotTone: 'bg-primary',
    title: 'Kernel Panic: Buffer Overflow',
    description: 'Exploit a heap-based buffer overflow in a custom Linux driver to achieve ring-0 privilege escalation and maintain persistence.',
    xp: '2,500 XP',
    difficulty: 'Hard',
    estimateTime: '120 minutes',
    environment: 'Linux Kernel Lab',
    categoryTag: 'Binary Exploitation',
    tags: ['Binary', 'Exploitation'],
    requiredKeywords: ['heap', 'overflow', 'escalation'],
    content: {
      markdown: '# Kernel Panic: Buffer Overflow',
      html: '<section><h2>Buffer Overflow Exploitation</h2></section>',
      missionOverview: '',
      remediationProtocols: '',
      vulnerabilityBriefing: { definition: '', impact: '' },
      technicalDeepDive: '',
    },
  },
  {
    id: 'ghost-in-the-ram',
    slug: 'ghost-in-the-ram',
    category: 'Digital Forensics',
    level: 'Medium',
    levelTone: 'text-amber-600',
    dotTone: 'bg-amber-500',
    title: 'Ghost in the RAM',
    description: 'Examine a captured memory dump from a compromised workstation. Identify the malicious process and recover the exfiltrated file.',
    xp: '1,000 XP',
    difficulty: 'Medium',
    estimateTime: '75 minutes',
    environment: 'Forensics Workbench',
    categoryTag: 'Digital Forensics',
    tags: ['Forensics', 'Memory'],
    requiredKeywords: ['memory dump', 'process analysis'],
    content: {
      markdown: '# Ghost in the RAM',
      html: '<section><h2>Digital Forensics</h2></section>',
      missionOverview: '',
      remediationProtocols: '',
      vulnerabilityBriefing: { definition: '', impact: '' },
      technicalDeepDive: '',
    },
  },
]

export const defaultCareerPaths = [
  {
    id: 'red-team-operator',
    slug: 'red-team-operator',
    title: 'RED TEAM OPERATOR',
    description: 'Master the art of adversary simulation. This path guides you through advanced reconnaissance, initial access, persistence, and exfiltration techniques used by state-sponsored threat actors.',
    icon: 'security',
    learningPathLevel: 'Expert',
    difficulty: 'Advanced',
    estimatedHours: 120,
    enrolledCount: 14209,
    mastery: 12,
    color: 'primary',
    modules: [
      {
        id: 'mod-01',
        phase: 'Module 01',
        title: 'Network Reconnaissance',
        description: 'Network mapping and target identification',
        rooms: ['sql-injection-the-basement', 'broken-keypad-rsa-101'],
      },
      {
        id: 'mod-02',
        phase: 'Module 02',
        title: 'Initial Access',
        description: 'Exploitation and initial foothold',
        rooms: ['kernel-panic-buffer-overflow', 'ghost-in-the-ram'],
      },
    ],
    resources: [
      { id: 'res-01', title: 'MITRE ATT&CK Framework', url: '#', type: 'Reference' },
      { id: 'res-02', title: 'Advanced Exploitation Guide', url: '#', type: 'Guide' },
    ],
  },
  {
    id: 'soc-architect',
    slug: 'soc-architect',
    title: 'SOC ARCHITECT',
    description: 'Defensive infrastructure, threat hunting, and incident response orchestration for state-level assets.',
    icon: 'shield',
    learningPathLevel: 'Expert',
    difficulty: 'Advanced',
    estimatedHours: 100,
    enrolledCount: 8950,
    mastery: 45,
    color: 'secondary',
    modules: [
      {
        id: 'mod-03',
        phase: 'Module 01',
        title: 'Threat Detection',
        description: 'Detection strategies and analytics',
        rooms: [],
      },
    ],
    resources: [],
  },
  {
    id: 'threat-intelligence',
    slug: 'threat-intelligence',
    title: 'THREAT INTELLIGENCE',
    description: 'Adversary profiling, tactical intelligence gathering, and strategic assessment for operational planning.',
    icon: 'visibility',
    learningPathLevel: 'Intermediate',
    difficulty: 'Intermediate',
    estimatedHours: 80,
    enrolledCount: 6240,
    mastery: 0,
    color: 'tertiary',
    modules: [],
    resources: [],
  },
]
