export const defaultJobListings = [
  {
    slug: 'ibm-soc-analyst-tier-1',
    title: 'SOC Analyst - Tier 1',
    company: 'IBM',
    location: 'Remote (US)',
    salary: '$55,000 - $75,000/yr',
    jobType: 'Entry Level',
    category: 'Cybersecurity',
    workMode: 'Remote',
    applyUrl: 'https://www.ibm.com/employment/',
    aboutRole:
      'IBM Security provides managed SOC services to enterprises globally. As a Tier 1 SOC Analyst, you monitor alerts, triage incidents, and escalate threats to senior analysts.',
    responsibilities: [
      'Monitor security dashboards and SIEM alerts in real time',
      'Triage incoming alerts and determine if they are genuine threats or false positives',
      'Document security incidents and create detailed incident tickets',
      'Escalate confirmed threats to Tier 2 analysts with full context',
      'Follow incident response playbooks for common attack scenarios',
      'Support threat intelligence feeds and update detection rules',
    ],
    requirements: [
      "Bachelor's degree in CS, IT, or Cybersecurity, or equivalent bootcamp/cert",
      'CompTIA Security+ certification required or in progress',
      'Familiarity with TCP/IP, DNS, HTTP, and firewalls',
      'Ability to work rotating shifts',
      'Strong written communication for incident documentation',
      '0-2 years experience',
    ],
    skills: [
      'SIEM',
      'Splunk',
      'QRadar',
      'Log analysis',
      'Incident triage',
      'Networking fundamentals',
      'Windows',
      'Linux',
      'Threat intelligence',
      'ServiceNow',
    ],
  },
  {
    slug: 'deloitte-junior-cybersecurity-analyst',
    title: 'Junior Cybersecurity Analyst',
    company: 'Deloitte',
    location: 'Hybrid - Multiple US cities',
    salary: '$65,000 - $85,000/yr',
    jobType: 'Entry Level',
    category: 'Cybersecurity',
    workMode: 'Hybrid',
    applyUrl: 'https://www2.deloitte.com/us/en/careers.html',
    aboutRole:
      "Deloitte's Cyber & Strategic Risk practice helps Fortune 500 clients defend against evolving cyber threats through assessments, GRC work, reports, and simulations.",
    responsibilities: [
      'Assist senior consultants on client security assessments',
      'Conduct vulnerability scanning and analyze results',
      'Support GRC engagements',
      'Research emerging threat actors and attack techniques',
      'Prepare client-facing security reports and dashboards',
      'Participate in tabletop exercises and incident simulations',
    ],
    requirements: [
      "Bachelor's degree in Cybersecurity, IT, Computer Science, or related field",
      'CompTIA Security+ or Google Cybersecurity Certificate',
      '0-1 years of hands-on security experience or internship',
      'Willingness to travel up to 20%',
      'Report writing and client communication',
    ],
    skills: [
      'Vulnerability scanning',
      'Nessus',
      'Qualys',
      'Risk assessment',
      'NIST CSF',
      'ISO 27001',
      'Report writing',
      'Microsoft Defender',
      'Security awareness',
    ],
  },
  {
    slug: 'microsoft-information-security-analyst-entry-level',
    title: 'Information Security Analyst (Entry Level)',
    company: 'Microsoft',
    location: 'Redmond, WA / Remote',
    salary: '$78,000 - $100,000/yr',
    jobType: 'Entry Level',
    category: 'Cybersecurity',
    workMode: 'Remote',
    applyUrl: 'https://careers.microsoft.com/',
    aboutRole:
      "Microsoft's Security organization processes large-scale security signals. This role supports detection and response in the Microsoft Security Response Center.",
    responsibilities: [
      'Investigate alerts from Microsoft Sentinel and Defender',
      'Analyze endpoint telemetry across Windows, Azure, and M365',
      'Support incident response and reviews',
      'Contribute to threat hunts using KQL',
      'Collaborate with product teams on security signal quality',
      'Produce shift handoff reports and knowledge base articles',
    ],
    requirements: [
      'BS in Computer Science, Cybersecurity, or Information Systems',
      'Familiarity with Sentinel, Defender, and Entra ID',
      'PowerShell or Python scripting',
      'CompTIA Security+, SC-200, or AZ-900',
      'Strong analytical thinking',
      '0-2 years experience',
    ],
    skills: [
      'Microsoft Sentinel',
      'KQL',
      'PowerShell',
      'Azure fundamentals',
      'Threat hunting',
      'EDR',
      'Incident response',
      'Python',
    ],
  },
  {
    slug: 'accenture-grc-analyst-entry-level',
    title: 'GRC Analyst - Entry Level',
    company: 'Accenture',
    location: 'Remote / Multiple locations',
    salary: '$60,000 - $80,000/yr',
    jobType: 'Entry Level',
    category: 'Cybersecurity',
    workMode: 'Remote',
    applyUrl: 'https://www.accenture.com/us-en/careers',
    aboutRole:
      'Accenture Security helps clients meet compliance mandates and manage risk. This GRC role focuses on governance, risk, compliance, documentation, and control mapping.',
    responsibilities: [
      'Support client risk assessments and control testing',
      'Map controls to NIST, ISO 27001, SOC 2, and HIPAA',
      'Assist third-party vendor risk assessments',
      'Document policies and procedures',
      'Track remediation in GRC platforms',
      'Present findings to stakeholders under supervision',
    ],
    requirements: [
      "Bachelor's degree in Business, IT, Cybersecurity, or Risk Management",
      'Understanding of compliance frameworks',
      'Microsoft Excel and PowerPoint skills',
      'Excellent written and verbal communication',
      'Willingness to obtain CISA or Security+',
      '0-2 years experience',
    ],
    skills: [
      'Risk assessment',
      'NIST CSF',
      'ISO 27001',
      'Archer',
      'Microsoft Excel',
      'Policy documentation',
      'Vendor risk management',
      'SOC 2',
    ],
  },
  {
    slug: 'aws-junior-devops-engineer',
    title: 'Junior DevOps Engineer',
    company: 'Amazon (AWS)',
    location: 'Seattle, WA / Hybrid',
    salary: '$90,000 - $115,000/yr',
    jobType: 'Entry Level',
    category: 'DevOps',
    workMode: 'Hybrid',
    applyUrl: 'https://amazon.jobs/',
    aboutRole:
      'AWS infrastructure teams hire junior DevOps engineers to build and maintain cloud infrastructure, CI/CD pipelines, automation, and reliability workflows.',
    responsibilities: [
      'Assist in building CI/CD pipelines using Jenkins and GitHub Actions',
      'Provision cloud infrastructure via Terraform and CloudFormation',
      'Monitor production systems using CloudWatch, Datadog, and PagerDuty',
      'Automate operations tasks with Python and Bash',
      'Participate in on-call after ramp-up',
      'Collaborate with software teams to improve deployment reliability',
    ],
    requirements: [
      'BS in Computer Science, Software Engineering, or related field',
      'Linux system administration',
      'Python or Bash scripting',
      'Docker fundamentals',
      'AWS Cloud Practitioner or equivalent hands-on knowledge',
      '0-2 years DevOps, cloud, or systems administration experience',
    ],
    skills: [
      'AWS',
      'EC2',
      'S3',
      'Lambda',
      'EKS',
      'Docker',
      'Terraform',
      'CI/CD',
      'Jenkins',
      'GitHub Actions',
      'Python',
      'Bash',
      'Linux administration',
      'CloudWatch',
      'Datadog',
      'Git',
    ],
  },
  {
    slug: 'google-associate-devops-engineer',
    title: 'Associate DevOps Engineer',
    company: 'Google (GCP)',
    location: 'Remote (US/Global)',
    salary: '$95,000 - $120,000/yr',
    jobType: 'Entry Level',
    category: 'DevOps',
    workMode: 'Remote',
    applyUrl: 'https://careers.google.com/',
    aboutRole:
      "Google's SRE and Infrastructure teams use this associate role for GCP infrastructure, reliability, deployment workflows, observability, and runbook work.",
    responsibilities: [
      'Support deployment and management of GCP infrastructure',
      'Implement CI/CD workflows using Cloud Build and GitLab CI',
      'Write infrastructure-as-code with Terraform',
      'Monitor systems using Cloud Monitoring and Prometheus/Grafana',
      'Contribute to runbooks and incident post-mortems',
      'Work with teams on reliability improvements',
    ],
    requirements: [
      'BS/MS in Computer Science, Engineering, or equivalent experience',
      'Hands-on GCP experience',
      'Python, Go, or Bash scripting',
      'Working knowledge of Kubernetes',
      'GCP Associate Cloud Engineer preferred',
      '0-2 years experience',
    ],
    skills: [
      'Google Cloud Platform',
      'GCP',
      'Kubernetes',
      'GKE',
      'Terraform',
      'CI/CD',
      'GitLab CI',
      'Cloud Build',
      'Python',
      'Go',
      'Prometheus',
      'Grafana',
      'Docker',
      'Linux',
    ],
  },
  {
    slug: 'infosys-cloud-devops-engineer-new-grad',
    title: 'Cloud DevOps Engineer - New Grad',
    company: 'Infosys',
    location: 'Hybrid - US / India',
    salary: '$70,000 - $90,000/yr (US) | Rs. 6-9 LPA (India)',
    jobType: 'Entry Level',
    category: 'DevOps',
    workMode: 'Hybrid',
    applyUrl: 'https://www.infosys.com/careers/',
    aboutRole:
      'Infosys Cobalt cloud practice hires new-grad DevOps engineers for enterprise cloud transformation, multi-cloud migration, automation, and delivery teams.',
    responsibilities: [
      'Set up and maintain CI/CD pipelines',
      'Automate infrastructure provisioning using Ansible and Terraform',
      'Monitor application health and respond to incidents',
      'Support migration of on-prem workloads to cloud',
      'Write deployment process and runbook documentation',
      'Collaborate in Agile/Scrum teams',
    ],
    requirements: [
      "Bachelor's in Engineering or Computer Science",
      'Minimum 60% or 6 CGPA throughout academics',
      'Exposure to AWS, Azure, or GCP',
      'Basic containerization and scripting knowledge',
      'AWS Cloud Practitioner or AZ-900 preferred',
      'Strong communication skills',
    ],
    skills: [
      'AWS',
      'Azure',
      'GCP',
      'Ansible',
      'Terraform',
      'Docker',
      'Jenkins',
      'Linux',
      'Python',
      'Bash',
      'Agile',
      'Scrum',
    ],
  },
  {
    slug: 'booz-allen-devsecops-engineer-entry-level',
    title: 'DevSecOps Engineer - Entry Level',
    company: 'Booz Allen Hamilton',
    location: 'Washington DC / Hybrid',
    salary: '$75,000 - $95,000/yr',
    jobType: 'Entry Level',
    category: 'DevOps + Cybersecurity',
    workMode: 'Hybrid',
    applyUrl: 'https://careers.boozallen.com/',
    aboutRole:
      'Booz Allen Hamilton blends DevOps engineering with security in this role, focusing on CI/CD security, container scanning, compliance automation, and secure SDLC.',
    responsibilities: [
      'Integrate SAST and DAST into CI/CD pipelines',
      'Manage container security and image scanning in Kubernetes',
      'Implement compliance-as-code with Chef InSpec or similar tools',
      'Support FedRAMP and DoD compliance automation',
      'Monitor cloud environments for security drift',
      'Collaborate on secure SDLC practices',
    ],
    requirements: [
      'BS in Computer Science, Cybersecurity, IT, or equivalent experience',
      'US citizenship required',
      'Cloud familiarity, AWS GovCloud preferred',
      'Security scanning tool basics',
      'Containerization and Kubernetes basics',
      'CompTIA Security+ or willingness to obtain',
    ],
    skills: [
      'CI/CD security',
      'SAST',
      'DAST',
      'Kubernetes',
      'AWS GovCloud',
      'Container scanning',
      'Trivy',
      'Snyk',
      'Terraform',
      'Compliance-as-code',
      'Python',
      'Bash',
      'FedRAMP',
      'DevSecOps',
    ],
  },
]

export function buildJobMarkdown(job) {
  return `# ${job.title}

**Company:** ${job.company}
**Location:** ${job.location}
**Salary:** ${job.salary}
**Type:** ${job.jobType} | ${job.category} | ${job.workMode}
**Apply:** ${job.applyUrl}

## About the Role
${job.aboutRole}

## Responsibilities
${job.responsibilities.map((item) => `- ${item}`).join('\n')}

## Requirements
${job.requirements.map((item) => `- ${item}`).join('\n')}

## Key Skills
${job.skills.map((item) => `\`${item}\``).join(' ')}
`
}
